# Generated by Django 5.1.2 on 2024-11-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatdrinkcanido', '0002_drink_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='recipe',
            field=models.TextField(default='', max_length=350),
        ),
    ]
