# Generated by Django 5.1.2 on 2024-11-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatdrinkcanido', '0006_alter_drink_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/drink_pictures/'),
        ),
    ]
